### ISSUE TITLE
Rename "defaultExt"

### ISSUE THREAD

**Issue by adamhalasz** [Nosthertus/diet-static-stream#5]
Just a small thing and it's just a suggestion. I personally prefer variable names especially if they are part of a Standard to be written out completely.

I suggest these names for this option to make it look more simple and elegant:
- **extension** - short and moderately descriptive
- **default** - very short and slightly descriptive
- **defaultExtension** - a bit long and very descriptive

Kind Regards,
Adam

**Comment by oscarr-reyes** [comment]
Hey Adam, thanks for your suggestions.. I am used to give very short names when it comes to naming variables with 2 words, but given about your explanation on how descriptive they can be, i come to think that i must make the public names as descriptive and possible, as long as they are not too long

Regards
Oscar Reyes
