### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by adamhalasz** [Nosthertus/diet-static-stream#6]
Unit test coverage is very essential and it's one of the first things people look for when trying out a project/module. If you make this module have unit tests it will make this module much more stable and valuable.

I'm not sure how much experience you have with Unit Testing but here are some resources that might help you if you don't know them already.

You can use mocha to write the tests and with expect your tests will look human readable:
- https://mochajs.org/
- https://github.com/Automattic/expect.js

You can use these tools to check your coverage. Istanbul is pretty awesome. It works seamlessly with mocha and it will generate a report for you showing line by line which parts of your code have unit test coverage and which don't. You can push your results to Coveralls which will give you a badge you can display on the project to show people how much of the code is covered. I use these with Diet as well.
- https://github.com/gotwarlost/istanbul
- https://coveralls.io/

You can also hook the project into Travis which will run the tests for you whenever you push code to the repo. Travis also gives you a nice badge!
- https://travis-ci.org/

Here are some tutorials:
- https://semaphoreci.com/community/tutorials/getting-started-with-node-js-and-mocha
- http://webapplog.com/tdd/

Thanks,
Adam

**Comment by oscarr-reyes** [comment]
Hey Adam.. thanks for checking on my module

For your question about Unit Testing, i have little experience with it and mostly i have been making programs to take care about tests, as i don't have much time to explore about other Node.js packages, i fail to know all features that `mocha` and `expect` can do, although i have heard about them alot.

I will look forward to study on all of them and soon i will give results to the public

Regards
Oscar Reyes

**Comment by adamhalasz** [comment]
Hey @Nosthertus thanks for the fast reply. That's ok, no rush! It's very valuable skill to learn and it will make your code quality much higher everywhere + you'll feel confident about your code like never before. It's an awesome feeling 😄 

Let me know if you have any questions. By the way if you make the Unit Tests and some Benchmarks VS `diet-static` I would be happy to replace `diet-static` with this as the Official Static Module and add it to the Diet Docs as well.

Good job so far by the way! I'm impressed 👍 

Cheers,
Adam

**Comment by oscarr-reyes** [comment]
Hey @adamhalasz Thanks again for suggesting these tools

i just added the tests results along with coveralls, you can check them out now
